"""inference.py

Helpers to run inference over a pgmpy model (VariableElimination).
This module uses the DiscreteBayesianNetwork model generated by
`graph_builder.py`.
"""

import pickle
from pgmpy.inference import VariableElimination
from pgmpy.models import DiscreteBayesianNetwork


CORE_NODES = [
    "UserAge",
    "UserGender",
    "HouseholdType",
    "TimeOfDay",
    "DayType",
    "ProgramType",
    "ProgramGenre",
    "ProgramDuration",
]

def _core_model(full_model: DiscreteBayesianNetwork) -> DiscreteBayesianNetwork:
    # Subgrafo inducido por CORE_NODES
    core_edges = [e for e in full_model.edges() if e[0] in CORE_NODES and e[1] in CORE_NODES]
    core = DiscreteBayesianNetwork(core_edges)

    # Copiar CPDs del modelo completo (solo las del core)
    core_cpds = [cpd for cpd in full_model.get_cpds() if cpd.variable in CORE_NODES]
    core.add_cpds(*core_cpds)

    # IMPORTANTE: que el core sea válido
    core.check_model()
    return core

def load_model_from_pickle(path: str):
    """Load a model saved with pickle."""
    with open(path, "rb") as f:
        model = pickle.load(f)
    return model


def run_query(model, variables, evidence=None):
    """Run a conditional marginal probability query on the model.
    variables: list of variable names to query.
    evidence: dict mapping variable->value.
    Returns the VariableElimination.query result (pgmpy object).
    """
    core = _core_model(model)
    infer = VariableElimination(core)
    result = infer.query(variables=variables, evidence=evidence or {})
    return result


if __name__ == "__main__":

    model_path = "main/outputs/model.pkl"
    model = load_model_from_pickle(model_path)


    observations = {
        "UserAge": "young",
        "UserGender": "male",
        "ProgramDuration": "long",
    }

    result = run_query(model, variables=["ProgramGenre"], evidence=observations)
    
    print("\nRecommended genre for the user:")
    print(result)
