"""inference.py

Helpers to run inference over a pgmpy model (VariableElimination).
This module uses the DiscreteBayesianNetwork model generated by
`graph_builder.py`.
"""

import pickle
from pgmpy.inference import VariableElimination
from pgmpy.models import DiscreteBayesianNetwork


CORE_NODES = [
    "UserAge",
    "UserGender",
    "HouseholdType",
    "TimeOfDay",
    "DayType",
    "ProgramType",
    "ProgramGenre",
    "ProgramDuration",
]

def load_model_from_pickle(path: str):
    """Load a model saved with pickle."""
    with open(path, "rb") as f:
        model = pickle.load(f)
    return model


def run_query(model, variables, evidence=None):
    """Run a conditional marginal probability query on the model.
    variables: list of variable names to query.
    evidence: dict mapping variable->value.
    Returns the VariableElimination.query result (pgmpy object).
    """
    infer = VariableElimination(model)
    result = infer.query(variables=variables, evidence=evidence or {})
    return result


if __name__ == "__main__":

    model_path = "main/outputs/model.pkl"
    model = load_model_from_pickle(model_path)


    observations = {
        "UserAge": "young",
        "UserGender": "male",
        "ProgramDuration": "long",
    }

    result = run_query(model, variables=["ProgramGenre"], evidence=observations)
    
    print("\nRecommended genre for the user:")
    print(result)
